@startuml test

hide circle
hide empty members
hide empty methods

skinparam classAttributeIconSize 0

skinparam roundcorner 5

skinparam class {
	BackgroundColor AliceBlue
	BorderColor DarkSlateGray
	ArrowColor Black
	FontColor Black
	FontSize 12
	FontName Helvetica
}

skinparam arrow {
    MessageAlign center
}



class Chantier{  
	date debut
    date fin 
    adresse
}

class Artisan{
    salaire horaire
    coordonnées
}

class Entreprise{
}

Entreprise --> Chantier
Entreprise --> Artisan

@enduml